places/urls.py
from django.conf.urls import url
from places import views

urlpatterns=[
    url(r'^$',views.index,name="placeshome"),
    url(r'^addplace',views.addplace,name="addplace"),
    url(r'^viewplaces',views.viewplaces,name="viewplaces"),
    url(r'^viewplace/(?P<id>\d+)/$',views.viewplace,name="viewplace"),
    url(r'^viewplace/placevote',views.placevote,name="voteforplace"),
]

workplace_data/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from workplace_data import views

urlpatterns = [
    url(r'^$',views.index,name="mainindex"),
    url(r'^admin/', admin.site.urls),
    url(r'^wusers/',include('wusers.urls')),
    url(r'^places/',include('places.urls')),
    url(r'^points/',include('points.urls')),
    url(r'^messages/',include('contactmeans.urls')),
]

places/forms.py
from django import forms
from places.models import Places

class AddPlace(forms.Form):
    company     =forms.CharField    ()
    country     =forms.CharField    ()
    state       =forms.CharField    ()
    city        =forms.CharField    ()
    address     =forms.CharField    ()

    class Meta:
        model=Places
        exclude=('wuser','wusersupvoted','wusersdownvoted',)

wusers/forms.py
from django import forms
from django.contrib.auth.models import User
from wusers.models import Wusers
from workplace_data import settings
from django.template import Template,Context
from django.shortcuts import render
from django.core.mail import send_mail
import os
import datetime
import hashlib

class RegistrationForm(forms.ModelForm):
    password    =forms.CharField    (widget=forms.PasswordInput())
    username    =forms.CharField    ()
    email       =forms.EmailField   ()
    first_name  =forms.CharField    (required=False)
    last_name   =forms.CharField    (required=False)

    class Meta:
        model=Wusers
        exclude=('user','reputation','activation_key','key_expires')

    def save(self,datas):
        u=User.objects.create_user(username=datas['username'],email=datas['email'],first_name=datas['first_name'],last_name=datas['last_name'])
        u.set_password(datas['password'])
        u.is_active=False
        u.save()
        wuser=Wusers(user=u,country=datas['country'],activation_key=datas['activation_key'],key_expires=datetime.datetime.strftime(datetime.datetime.now() + datetime.timedelta(days=2), "%Y-%m-%d %H:%M:%S"))
        wuser.save()
        return u

    def sendEmail(self,datas):
        link="http://127.0.0.1:8000/wusers/activate/"+datas['activation_key']
        c=Context({'activation_link':link,'username':datas['username']})
        f=open(os.path.join(settings.TEMPLATE_DIR,datas['email_path']),'r')
        t=Template(f.read())
        f.close()
        message=t.render(c)
        send_mail(datas['email_subject'],message,'somedomain',[datas['email']],fail_silently=False)

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<header>
  <title>{% block title %}{% endblock %}</title>
  {% block css %}{% endblock %}
  {% block header_javascript %}{% endblock %}
  {% include 'jslibraries.html' %}
  {% include 'csslibraires.html' %}
  <link rel="stylesheet" href="{% static 'main/css/common_css.css' %}">
</header>
<body>

	<nav role="navigation" class="navbar navbar-custom col-md-10 col-md-offset-1">
		<div class="container-fluid">
			
			<div class="navbar-header">
				<a href="{% url 'mainindex' %}" class="navbar-brand">WorkPlace Data</a>
			</div>

			<div class="row">

				{% if not user.is_authenticated %}
					<ul class="nav navbar-nav navbar-right">
						<li> <a href="#" class="login-toggle">Login</a> </li>
						<li> <a href="#" class="register-toggle">Register</a> </li>
					</ul>
				{% endif %}

				{% if user.is_authenticated %}
					<ul class="nav navbar-nav">

						<li class="dropdown ">
							<a class="dropdown-toggle unhovered" data-toggle="dropdown" href="#">Places<span class="caret"></span></a>

								<ul class="dropdown-menu">

									<li> <a href="{% url 'addplace' %}" class="">Add Place</a> </li>
									<li> <a href="{% url 'viewplaces' %}">View Places</a> </li>
									
								</ul>
						</li>

						<li class="dropdown ">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">Messages<span class="caret"></span></a>

								<ul class="dropdown-menu">

									<li> <a href="{% url 'viewsentmessages' %}">Sent</a> </li>
									<li> <a href="{% url 'viewreceivedmessages' %}">Recieved</a> </li>
									
								</ul>
						</li>
						
					</ul>

					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#">{{ request.user.username }}<span class="caret"></span></a>

								<ul class="dropdown-menu">

									<li> <a href="{% url 'viewprofile' wuser_id=request.user.id %}">Profile</a> </li>
									<li> <a href="{% url 'userpasswordreset' %}">Password Reset</a> </li>
									
								</ul>
						</li>

						<li> <a href="{% url 'userlogout' %}">Logout</a> </li>
					
					</ul>
				{% endif %}

			</div>

		</div>
	</nav>  


	<!-- <div class="container-fluid"> -->
	<div class="container-fluid">
	<div class="row">
	
		<div class="col-md-2 col-md-push-9 ">
			
			<div class="login-div col-md-12 ">
				<form action="{% url 'userlogin' %}" method="POST" class="side">
					{% csrf_token %}
					<legend><h2>Login</h2></legend>					

					<center>
						<input type="text" id="username" name="username"  placeholder="Username"> 

						<input type="password" name="password" id="password" placeholder="Password"> 					
						
					    <button type="submit" class="btn">Submit</button>
				    </center>
				    
				</form>
			</div>

			<div class="register-div col-md-12 ">
				<form action="{% url 'userregistration' %}" method="POST" class="side">
					{% csrf_token %}
					<legend><h2>Register</h2></legend>					

					<center>
						<input id="id_first_name" name="first_name" type="text" placeholder="First Name">

						<input id="id_last_name" name="last_name" type="text" placeholder="Last Name">

						<input id="id_country" maxlength="100" name="country" type="text" placeholder="Country">

						<input id="id_email" name="email" type="email" placeholder="Email">

						<input id="id_username" name="username" type="text" placeholder="Username">

						<input id="id_password" name="password" type="password" placeholder="Password">

						<button type="submit" class="btn">Submit</button>
					</center>
					
				</form>
			</div>

		</div>


		<div class="col-md-7 col-md-offset-2 content col-md-pull-2">	
			{% block content %}{% endblock %}
		</div>
	</div>
	</div> 
	

</body>
	<script>
		$(document).ready(function() {
			$(".navbar-custom .navbar-nav .dropdown").hoverIntent({
				sensitivity: 1,
				interval: 60,
				timeout: 150,
				over:function(){
					// $(this).addClass('open');
					$(this).find('.dropdown-menu').stop(true,true).fadeIn(200);
				},
				out:function() {
					// $(this).removeClass('open');
					$(this).find('.dropdown-menu').stop(true,true).fadeOut(150);
				}
			});

			$(".login-toggle").click(function() {
				if( $('.register-div').css('display') != 'none' ) {
					$(".register-div").fadeOut(150).delay(150);
					$(".register-div").css("display","none").delay(100);
					$(".login-div").fadeIn(200);
				}
				else if( $('.register-div').css('display') == 'none' && $('.login-div').css('display') == 'none') {
					$(".login-div").fadeIn(200);
				}
			});

			$(".register-toggle").click(function() {
				if( $('.login-div').css('display') != 'none' ) {
					$(".login-div").fadeOut(150).delay(150);
					$(".login-div").css("display","none").delay(100);
					$(".register-div").fadeIn(200);
				}
				else if( $('.login-div').css('display') == 'none' && $('.register-div').css('display') == 'none') {
					$(".register-div").fadeIn(200);
				}
			});
		})
	</script>
	{% block footer_javascript %}{% endblock %}
</html>

templates/csslibraires.html
{% load staticfiles %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!-- <link rel="stylesheet" href="{% static 'main/css/common_css.css' %}"> -->

templates/jslibraries.html
{% load staticfiles %}
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="{% static 'main/js/jquery.hoverIntent.minified.js' %}"></script>

templates/reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}